"""Python tools for inspecting and translating Adobe Illustrator files."""

from .assets import PackagedLink, iter_linked_images, package_linked_images
from .authoring import (
    AffineTransform,
    AreaTextBlock,
    FontSpec,
    LayerBuilder,
    RenderedComponent,
    Table,
    TableColumn,
    TableStyle,
    TextBlock,
    TextStyle,
    ellipse_path,
    polyline_path,
    rectangle_path,
    transform_group,
    transform_image,
    transform_path,
    transform_text,
)
from .compatibility import (
    LegacyDiagnostic,
    LegacyFeatureOccurrence,
    LegacyFieldOrigin,
    LegacyNodeOrigin,
    LegacyParseCoverage,
    LegacyReadResult,
)
from .format import FileFormat, FormatReport, inspect_file
from .legacy import (
    ReplaceLinkedImageSource,
    ReplaceText,
    SetPathFill,
    SetPathStroke,
    TranslateContainer,
    TranslatePath,
    patch_container_translate,
    patch_linked_image_source,
    patch_path_fill,
    patch_path_stroke,
    patch_path_translate,
    patch_text,
    read_ai7,
    reserialize_ai7,
)
from .lossless import (
    LegacyLineToken,
    LegacySource,
    SourceLimitExceeded,
    SourceReplacement,
    tokenize_legacy,
)
from .model import (
    Artboard,
    ClippingGroup,
    CmykColor,
    Color,
    CompoundPath,
    ControlPoint,
    Document,
    Group,
    Layer,
    LayerItemRef,
    LinkedImage,
    Path,
    Point,
    TextFrame,
)
from .semantic import SemanticDiff, SemanticDifference, semantic_diff

__all__ = [
    "Artboard",
    "CmykColor",
    "AffineTransform",
    "AreaTextBlock",
    "Color",
    "CompoundPath",
    "ControlPoint",
    "ClippingGroup",
    "Document",
    "FileFormat",
    "FontSpec",
    "FormatReport",
    "Group",
    "Layer",
    "LayerBuilder",
    "LayerItemRef",
    "LinkedImage",
    "LegacyLineToken",
    "LegacyDiagnostic",
    "LegacyFeatureOccurrence",
    "LegacyFieldOrigin",
    "LegacyNodeOrigin",
    "LegacyParseCoverage",
    "LegacyReadResult",
    "LegacySource",
    "Path",
    "PackagedLink",
    "Point",
    "RenderedComponent",
    "ReplaceLinkedImageSource",
    "ReplaceText",
    "TextFrame",
    "TextBlock",
    "TextStyle",
    "SourceLimitExceeded",
    "SourceReplacement",
    "SetPathFill",
    "SetPathStroke",
    "SemanticDiff",
    "SemanticDifference",
    "Table",
    "TableColumn",
    "TableStyle",
    "TranslateContainer",
    "TranslatePath",
    "ellipse_path",
    "inspect_file",
    "iter_linked_images",
    "package_linked_images",
    "patch_container_translate",
    "patch_path_fill",
    "patch_path_stroke",
    "patch_path_translate",
    "patch_linked_image_source",
    "patch_text",
    "polyline_path",
    "rectangle_path",
    "read_ai7",
    "reserialize_ai7",
    "semantic_diff",
    "transform_group",
    "transform_image",
    "transform_path",
    "transform_text",
    "tokenize_legacy",
]

__version__ = "0.1.0.dev0"
