"""Python tools for inspecting and translating Adobe Illustrator files."""

from .assets import PackagedLink, iter_linked_images, package_linked_images
from .authoring import (
    AffineTransform,
    AreaTextBlock,
    FontSpec,
    LayerBuilder,
    RenderedComponent,
    Table,
    TableColumn,
    TableStyle,
    TextBlock,
    TextStyle,
    ellipse_path,
    polyline_path,
    rectangle_path,
    transform_group,
    transform_image,
    transform_path,
    transform_text,
)
from .format import FileFormat, FormatReport, inspect_file
from .lossless import (
    LegacyLineToken,
    LegacySource,
    SourceLimitExceeded,
    SourceReplacement,
    tokenize_legacy,
)
from .model import (
    Artboard,
    ClippingGroup,
    CmykColor,
    Color,
    CompoundPath,
    ControlPoint,
    Document,
    Group,
    Layer,
    LayerItemRef,
    LinkedImage,
    Path,
    Point,
    TextFrame,
)

__all__ = [
    "Artboard",
    "CmykColor",
    "AffineTransform",
    "AreaTextBlock",
    "Color",
    "CompoundPath",
    "ControlPoint",
    "ClippingGroup",
    "Document",
    "FileFormat",
    "FontSpec",
    "FormatReport",
    "Group",
    "Layer",
    "LayerBuilder",
    "LayerItemRef",
    "LinkedImage",
    "LegacyLineToken",
    "LegacySource",
    "Path",
    "PackagedLink",
    "Point",
    "RenderedComponent",
    "TextFrame",
    "TextBlock",
    "TextStyle",
    "SourceLimitExceeded",
    "SourceReplacement",
    "Table",
    "TableColumn",
    "TableStyle",
    "ellipse_path",
    "inspect_file",
    "iter_linked_images",
    "package_linked_images",
    "polyline_path",
    "rectangle_path",
    "transform_group",
    "transform_image",
    "transform_path",
    "transform_text",
    "tokenize_legacy",
]

__version__ = "0.1.0.dev0"
